const data = [
    {
        title: 'Pollo y Campinones',
        type: 'Lasagnas',
        id: 1,
        images: '/images/lasagna.jpg',
        recomended: false,
        price: 22000,
    },
    {
        title: 'Carne',
        type: 'Lasagnas',
        id: 2,
        images: '/images/lasagna1.jpg',
        recomended: false,
        price: 21000,
    },
    {
        title: 'Pollo ',
        type: 'Lasagnas',
        id: 3,
        images: '/images/lasagna2.jpg',
        recomended: false,
        price: 20000,
    },
    {
        title: 'Mixta',
        type: 'Lasagnas',
        id: 4,
        images: '/images/lasagna3.png',
        recomended: false,
        price: 22000,
    },
    {
        title: 'Pollo con Camarones',
        type: 'Pastas',
        id: 5,
        images: '/images/pastaPyCh.jpeg',
        recomended: true,
        price: 23000,
    },
    {
        title: 'Salsa Bolognesa',
        type: 'Pastas',
        id: 6,
        images: '/images/pasta1.jpg',
        recomended: false,
        price: 20000,
    },
    {
        title: 'Carbonara',
        type: 'Pastas',
        id: 7,
        images: '/images/pasta2.png',
        recomended: false,
        price: 22000,
    },
    {
        title: 'Solomito con Queso',
        type: 'Pastas',
        id: 8,
        images: '/images/pasta3.jpeg',
        recomended: true,
        price: 20000,
    },
    {
        title: 'Coca - Cola',
        type: 'Bebidas',
        id: 9,
        images: '/images/coca-cola .png',
        recomended: false,
        price: 8000,
    },
    {
        title: 'Limonada',
        type: 'Bebidas',
        id: 10,
        images: '/images/limonada.png',
        recomended: false,
        price: 7000,
    },
    {
        title: 'Soda Saborizada',
        type: 'Bebidas',
        id: 11,
        images: '/images/sodasSaborisadas.jpeg',
        recomended: false,
        price: 9000,
    },
    {
        title: 'Jugos Naturales',
        type: 'Bebidas',
        id: 12,
        images: '/images/jugo.jpg',
        recomended: false,
        price: 9500,
    },
    {
        title: 'Artesanal',
        type: 'Hamburguesas',
        id: 13,
        images: '/images/hArtesanal1.jpeg',
        recomended: true,
        price: 22000,
    },
    {
        title: 'Solomito',
        type: 'Hamburguesas',
        id: 14,
        images: '/images/hamburguesa1.png',
        recomended: false,
        price: 21000,
    },
    {
        title: 'Vegetariana',
        type: 'Hamburguesas',
        id: 15,
        images: '/images/hamburguesa2.jpg',
        recomended: false,
        price: 20000,
    },
    {
        title: 'Pollo y champiñones',
        type: 'Hamburguesas',
        id: 16,
        images: '/images/hamburguesa3.jpg',
        recomended: true,
        price: 23000,
    },
];

export default data;
