import React from 'react';
import Head from 'next/head';
import ProductFinder from '../components/ProductFinder';
import styles from '../styles/Home.module.css';

export default function Finder() {
    return (
        <div>
            <Head>
                <title>Smart Menu 2.0</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ProductFinder />
            <footer className={styles.footer}>
                <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
                    Desarrolado por Tonnys LAB{' '}
                </a>
            </footer>
        </div>
    );
}
