import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import ProductFinder from '../components/ProductFinder';

export default function Finder() {
    return (
        <div>
            <Head>
                <title>Smart Menu 2.0</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ProductFinder />
            <footer>
                <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
                    Powered by{' '}
                    <span>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    );
}
